service: firstserverlessproject

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  profile: serverlessUser

functions:
  hello:
    handler: handler.hello

plugins:
  - serverless-s3-sync

custom:
  s3Sync:
    - bucketName: firstserverlessproject-bucket
      localDir: uploads

resources:
  Resources:
    DemoBucketUpload:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: firstserverlessproject-bucket